runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT app:app
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10
